Anakarolcatu/pagina/cadastro
sQsquad/sQpets pull request #41
Opened 2024-04-23 22:41 UTC by anakarolcatu

Adicionando arquivo html e css da pagina de cadastro

2024-05-08 05:10 UTC, IngridOguro commented
Conflito resolvido, não sei por que, mas era a imagem de check da tarefa

2024-05-08 05:13 UTC, IngridOguro commented
Tem que ajustar a responsividade, na minha tela (1920x1080) fica assim:
![Captura de tela 2024-05-08 015709](https://github.com/sQsquad/sQpets/assets/62152558/08596ce1-1fac-40ff-a98e-baca4d14a230)

2024-05-08 05:20 UTC, IngridOguro requested changes
Precisa ajustar a responsividade.

2024-05-08 05:20 UTC, IngridOguro commented on pages/cadastro/cadastro_estilo.css
> +:root {
boa organização de cores

2024-05-08 05:20 UTC, IngridOguro commented on pages/cadastro/cadastro.html
> +        <main class="cadastro__main">
ajuste a indentação

2024-05-08 05:20 UTC, IngridOguro commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:1145px) {
Tem que ajustar a responsividade, na minha tela (1920x1080) fica assim:
![Captura de tela 2024-05-08 015709](https://github.com/sQsquad/sQpets/assets/62152558/08596ce1-1fac-40ff-a98e-baca4d14a230)

2024-05-10 14:36 UTC, anakarolcatu commented on pages/cadastro/cadastro.html
> +        <main class="cadastro__main">
corrigido

2024-05-10 14:41 UTC, anakarolcatu commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:1145px) {
Pode verificar novamente? Ajustei alguns parâmetros e testei em outro computador e ficou ok. Quando ao campo do email, acredito que só consigo corrigir qdo adicionar o javascript pq ele tá sobrepondo pois o valor não é válido. (se tiver outra maneira de resolver, eu não encontrei)

2024-06-17 17:42 UTC, IngridOguro requested changes
Ficou muito bom, acho que só precisa fazer um pequeno ajuste no query. De resto só o JavaScript mesmo. 👍

2024-06-17 17:42 UTC, IngridOguro commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:580px) {
Esse valor de 580 está duplicado

2024-06-17 17:42 UTC, IngridOguro commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:1145px) {
Vi que você alterou as cores, na minha tela ainda está grande.
![image](https://github.com/sQsquad/sQpets/assets/62152558/88b4d8ef-1c00-4ebd-959b-362ce2f60143)

Dá uma olhada no @media

2024-06-17 17:42 UTC, IngridOguro commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:580px) {
Aqui está o duplicado.

2024-06-17 17:42 UTC, IngridOguro commented on pages/cadastro/cadastro_estilo.css
> +
A responsividade para mobile ficou muito boa ! 😊

2024-06-18 22:08 UTC, anakarolcatu commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:580px) {
Corrigido!

2024-06-18 22:08 UTC, anakarolcatu commented on pages/cadastro/cadastro_estilo.css
> +@media (max-width:580px) {
Corrigido!

2024-06-18 22:09 UTC, anakarolcatu commented on pages/cadastro/cadastro_estilo.css
> +
Obrigada 😊

2024-06-18 22:13 UTC, anakarolcatu commented on pages/cadastro/cadastro_estilo.css
> +
Dá uma olhada se melhorou o tamanho. Reduzi o tamanho dos inputs

2024-07-23 02:08 UTC, closed without merging